### ISSUE TITLE
Suggestion: disable auto insert of END_VAR on typing VAR

### ISSUE THREAD

**Issue by msftrncs** [Serhioromano/vscode-st#10]
typing in VAR causes END_VAR to be instantly inserted, yet there is more to type, such as _INPUT.

Code snippets already exist to choose from, but the auto insert of END_VAR prevents them from being selected successfully, because the END_VAR that was auto inserted gets left after selection.  The code snippets works successfully if you type 'var' or stop before typing the R and make the selection then.

**Comment by Serhioromano** [comment]
Fixed in upcoming release. Thank you.
