### ISSUE TITLE
Keywords like TRUE and EXIT inside of comments get auto capitalized

### ISSUE THREAD

**Issue by tkucic** [Serhioromano/vscode-st#16]
Hi,
when i open the st code in vscode the auto keyword capitalizer is capitalizing also inside of the comments.
![image](https://user-images.githubusercontent.com/30636183/56980301-ae8f6900-6b84-11e9-8ad2-7e4e399034d7.png)

**Comment by Serhioromano** [comment]
Unfortunately, right now without LSP, I cannot detect either we are in comments or not. Later when I add LSP, it will autoindent, lint, autoformat and the rest of LSP goodies.
