### ISSUE TITLE
Suggestion for Beckhoff

### ISSUE THREAD

**Issue by anhphong2312** [Serhioromano/vscode-st#19]
Hi team,

Just wonder if this plugin works for Beckhoff Structured Text codes?

Thank you!

**Comment by niksosov** [comment]
It is just text editor. If Beckhoff supporting [IEC-61131-3](https://en.wikipedia.org/wiki/IEC_61131-3), then it is be working with him.

**Comment by Serhioromano** [comment]
It won't work directly. I mean most probably you will not be able to open Beckhoff project. But you can user this plugin to code, then copy\paste.
