### ISSUE TITLE
Incorrect auto formatting.

### ISSUE THREAD

**Issue by david9991** [Serhioromano/vscode-st#20]
Function name or maybe other place contains a keywords will be auto formatted to Upper characters.
for example:
`FUNCTION test_return_exit` will be auto formatted to `FUNCTION test_RETURN_EXIT`.

**Comment by Serhioromano** [comment]
I was working on new Formating algorithm utilizing VS Code built in API. I've release v1.8.0 of extension, that one should fix the issue and also formating is now standard VS Code formating menu option.

It does not do much, but at least there is new extension architecture. I'll advance it later when have more time.

**Comment by Serhioromano** [comment]
@david9991 please report after update if issue goes away.

**Comment by david9991** [comment]
@Serhioromano Yes, seems it never happen again.

**Comment by david9991** [comment]
@Serhioromano Hello, there is still some issue here. Keywords in quoted text still be formatted.

![Screenshot from 2020-09-15 09-04-12](https://user-images.githubusercontent.com/123219/93152938-8f21bd80-f732-11ea-89b9-5463c87eed82.png)

**Comment by Serhioromano** [comment]
Fixed in latest version 1.8.2
