### ISSUE TITLE
Invite for coloboration

### ISSUE THREAD

**Issue by Serhioromano** [Serhioromano/vscode-st#22]
Hi @philippranzhin,

You were a collaborator for another ST extension. You had few good ideas. I invite you to join this extension development. Please post your issues here and I'll try to improve extension.

**Comment by slimeth** [comment]
@Serhioromano are you looking for more collaborators?

**Comment by Serhioromano** [comment]
@slimeth I surely do! I want to implement LINT and formatting and go to definition. I mean I want implement LSP but I cannot completely understand how it works.
