### ISSUE TITLE
VAR/END_VAR scope when as parts of other identifiers

### ISSUE THREAD

**Issue by msftrncs** [Serhioromano/vscode-st#31]
`VAR` and `END_VAR` incorrectly scope when run in to other identifiers in certain orders

![image](https://user-images.githubusercontent.com/26179051/106551712-6fb9e000-64db-11eb-8e78-29c7667054e0.png)

`VAR` does not validate word break at end, `END_VAR` does not validate work break at either end.

`VAR_x` seem to be same as `VAR`

Looks like the \b is missing from the end of both the begin and end clauses.

**Comment by Serhioromano** [comment]
If you put all in one line not sure it is fixable. Scope is defined with JSON file, and basically as I understand it, VS Code takes care of scopes, open\close brackets.

**Comment by msftrncs** [comment]
https://github.com/Serhioromano/vscode-st/blob/f33afa298c99bbc60bc3b11f04945ef32df050f4/syntaxes/st.tmLanguage.json#L220-L226

```
"begin": "\\b(?:VAR(?:_(?:INPUT|OUTPUT|IN_OUT|TEMP|GLOBAL|ACCESS|EXTERNAL))?|STRUCT|UNION|PUBLIC|PRIVATE|PROTECTED)\\b", 
```
```
"end": "\\b(?:END_(?:VAR|STRUCT|UNION))\\b",
```

(different coloring here, but now the keywords run together are no longer 'keywords')
![image](https://user-images.githubusercontent.com/26179051/106570851-0eeecf80-64fc-11eb-8b75-d3f7c459c730.png)

**Comment by Serhioromano** [comment]
> (different coloring here, but now the keywords run together are no longer 'keywords')
> ![image](https://user-images.githubusercontent.com/26179051/106570851-0eeecf80-64fc-11eb-8b75-d3f7c459c730.png)

Is that how it supposed to behave? Looks correct to me. You can PR this change.

**Comment by msftrncs** [comment]
After Appling correction:

![image](https://user-images.githubusercontent.com/26179051/106572907-a0f7d780-64fe-11eb-8fdc-dd9815361387.png)
