### ISSUE TITLE
view Twincat *.TcPOU, *.TcDUT, etc...

### ISSUE THREAD

**Issue by runtimevic** [Serhioromano/vscode-st#35]
Hello, 
Are they contemplated to open with vscode and the extension Structured Text language Support the Twincat 3 blocks *.TcPOU, *.TcDUT, etc...?
thanks you.

**Comment by Serhioromano** [comment]
Updated to v. 1.10.2 with supports this file estensions.

**Comment by Serhioromano** [comment]
Your review will be appreciated!
https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-st&ssr=false#review-details

**Comment by Serhioromano** [comment]
So fast! I messed up v 1.10.2 so I release new one 1.10.3. Please update and confirm everything is working.
