### ISSUE TITLE
Suggestion, split view is VS code

### ISSUE THREAD

**Issue by r9guy** [Serhioromano/vscode-st#36]
Is it possible to split editor to 2 sections, like Visual Studio does?
This would be a step closer to separate Declaration from Definition.

**Comment by slimeth** [comment]
@r9guy suggestion seems actually quite relevant and would be not only cosmetically beneficial. TwinCAT seems rather sensitive on that XML code on top, between and after the declaration and definition. I realized that after I activated the auto-formatting of VS code which also formatted the XML code and afterward TwinCAT couldn't read the file properly anymore.
![TwinCAT](https://user-images.githubusercontent.com/32170546/139867956-422f9de3-91ef-4adc-bcf1-3a6428e5a890.png)
![VSCode](https://user-images.githubusercontent.com/32170546/139868409-fe833572-59f3-444a-ba34-de2a6c88ea4c.png)

**Comment by r9guy** [comment]
Not only that but TwinCAT may change some UIDs in that XML portion and
version control system must not be fooled by that.

**Comment by Serhioromano** [comment]
This is not easy to do for TwinCat. Because it stores files as XML files. Although perhaps that would make a lot of sense is files of this  extension is opened that way. Anyway right now I have no idea how I could pull this off.

**Comment by r9guy** [comment]
This case is closed, however I have seen the following project from Microsoft.
[Interactive](https://github.com/dotnet/interactive). 
they also have in preview stage extension for VX2022. basically what they have done is create notebook like environment for any programming language.

**Comment by Serhioromano** [comment]
I've seen this feature in VSC. But I still did not see a practical application for this case.
