### ISSUE TITLE
Using formatter issue

### ISSUE THREAD

**Issue by ChrisNiklasLucka** [Serhioromano/vscode-st#37]
Hi serhioromano,

I am using your program and it works really nice, but I have an issue using the formatter. How can I set um, that <> isn't change to < >? 

Thanks at first and BR
Chris

**Comment by Serhioromano** [comment]
Thank you. I have fixed in in next update by the end of this week.

**Comment by ChrisNiklasLucka** [comment]
Hi serhioromano,

great work, can you publish this extension with all updates to vs code extensions? 

Would be great. Thanks!

**Comment by Serhioromano** [comment]
I cannot. There is always an error. I still investigate what is going on.

**Comment by ChrisNiklasLucka** [comment]
ok then I keep my fingers crossed that this will work out in the near future

**Comment by Serhioromano** [comment]
@ChrisNiklasLucka 
Finally was able to publish 1.10.8 after full WSL reinstall.
