### ISSUE TITLE
Issue with **

### ISSUE THREAD

**Issue by ChrisNiklasLucka** [Serhioromano/vscode-st#38]
Hi Serhioromano,

I've also found an issue with the ** which is automatically changed to * *. Is there also an option, that you fix this?

By the way I have more topics for your grandious extension but I don't know if I can ask here for all these stuff and give you tasks, but I can't realize an extension by my own. Is there any interest from your side to realize some more stuff in this extension or should it be an running version and thats it?

Thanks for all your help and best regards
Chris

**Comment by Serhioromano** [comment]
Fixed/

**Comment by Serhioromano** [comment]
Finally was able to publish 1.10.8 after full WSL reinstall.

**Comment by ChrisNiklasLucka** [comment]
Great work @Serhioromano !
Did you read this: 
_By the way I have more topics for your grandious extension but I don't know if I can ask here for all these stuff and give you tasks, but I can't realize an extension by my own. Is there any interest from your side to realize some more stuff in this extension or should it be an running version and thats it? I read, that you want to realize an compiler, is there any update for this?

**Comment by ChrisNiklasLucka** [comment]
Hi @Serhioromano tested your new update and the formatter did not work now, is there another bug? Thanks to you!

**Comment by Serhioromano** [comment]
I'll test is now. You can create as many issues here as you wish, I'll be more than glad to solve all I can.

**Comment by Serhioromano** [comment]
Released 1.11.1 version should work. I have fully refactored spaces formating.

**Comment by ChrisNiklasLucka** [comment]
Hello @Serhioromano ** still changes to * *. Is there anything missing?

**Comment by ChrisNiklasLucka** [comment]
@Serhioromano thanks for the great work (i deleted my last comment, it was wrong). Thank you very much!
