### ISSUE TITLE
Incorrect semicolon position in REPEAT template

### ISSUE THREAD

**Issue by bforget163** [Serhioromano/vscode-st#39]
The semicolon(`;`) in REPEAR template should be placed after the `END_REPEAR` rather than the `UNTIL` expression. I tried this on both CODESYS V3.5 and Beremiz.

![1640054117(1)](https://user-images.githubusercontent.com/33746058/146861209-0104c6ba-629a-45fd-8d05-7f07bc0f98b5.png)

**Comment by Serhioromano** [comment]
Thanks for PR
