### ISSUE TITLE
Add support for lowercase keywords

### ISSUE THREAD

**Issue by AndersHogqvist** [Serhioromano/vscode-st#45]
Even though we are supposed to use capital letters in keywords such as IF, ELSIF etc we have a lot of files where these are written in lower case (if, elseif...). However the syntax highlighting only check for these words in capital letters.

**Comment by AndersHogqvist** [comment]
The only thing that needs to be done is to add `(?i)` at the beginning of all regex patterns in st.tmLanguage.json. Example:
`"match": "(?i)\\b(?:END_)?(?:IF|CASE|OF|ELSE|ELSIF|THEN|__TRY|__CATCH|__FINALLY|__ENDTRY)\\b"`

**Comment by Serhioromano** [comment]
Or you can click Shift+Alt+F and this extension will capitalize all needed keywords. This way is much better because although ST is not case sensitive, it would be nicer to have those keywords capitalized for code convention.

**Comment by AndersHogqvist** [comment]
> Or you can click Shift+Alt+F and this extension will capitalize all needed keywords. This way is much better because although ST is not case sensitive, it would be nicer to have those keywords capitalized for code convention.

Oh, didn't know about that. Thanks!

**Comment by Serhioromano** [comment]
@AndersHogqvist  Please I will very appreciate if you rate this extension here
https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-st&ssr=false#review-details
