### ISSUE TITLE
Variable with name containing TO is interpreted as a function

### ISSUE THREAD

**Issue by AndersHogqvist** [Serhioromano/vscode-st#47]
When a variable name contains `TO` the syntax highlighting will interpret and highlight it as a function.

**Comment by Serhioromano** [comment]
Can you show me an example I cannot reproduce. Also refer to theme you are using.

**Comment by AndersHogqvist** [comment]
I'm using the dark theme (of course ;-)) and here's some variables we have in one of the files:
https://app.box.com/s/i9thn748hh75fwj0xakesicw62ze2nnh

As you can see the first three variables are highlighted as functions and the rest as variables and that's because they contain _TO_

**Comment by Serhioromano** [comment]
Now I see what you mean. it is not `TO` but `_TO_` the reason. I'll try to fix it.

**Comment by Serhioromano** [comment]
I have released 1.12.14 version where I fixed number of things discovered because of your issue. Should be fine now.

**Comment by Serhioromano** [comment]
@AndersHogqvist please report if it works fine now.

**Comment by AndersHogqvist** [comment]
Yes sir, it works perfectly fine 🙂
