### ISSUE TITLE
Duration literals should be in small letters

### ISSUE THREAD

**Issue by AndersHogqvist** [Serhioromano/vscode-st#48]
The document format feature change the duration literals to capital letters but according to IEC 61131-3 (and us) they should be in small letters. Example:
`T#1s` becomes `T#1S`
`T#1ms` becomes `T#1MS`

**Comment by Serhioromano** [comment]
I am releasing new version nor 1.12.12 where it is fixed. Even more it now lowercase those letters. I did not know that about standard. In few IDEs it is all capitalized I thought it is how it should be.
