### ISSUE TITLE
How to integrate into Visual Studio

### ISSUE THREAD

**Issue by XFuel** [Serhioromano/vscode-st#53]
I'm really interested in getting this to work in Visual Studio and not Visual Studio Code. Can anyone help me with that?

**Comment by Serhioromano** [comment]
That all depends on what you mean by integration. Only syntax highlight or you want to build and download to PLC

**Comment by XFuel** [comment]
Just the syntax Highlighter, I’m using the TwinCAT shell in VS so that’s covered but I’m not so proficient in VS as to how to apply the syntax highlight

**Comment by Serhioromano** [comment]
Quick search shows that it is not a simple task to adopt this extension for VS. When I finish with LSP it might be more possible.
