### ISSUE TITLE
Formatting -  typo and extra features

### ISSUE THREAD

**Issue by Ahrkylien** [Serhioromano/vscode-st#55]
When formatting several missing features poped up

Two important rules from PLCopen.org:

- No space before semi-colon ';'
- No space before colon ':' . One space after if not located at line end

## Example 1:
```
VAR_INPUT
test: BOOL:=TRUE;
testNumberTwo:    BOOL   :=    TRUE   ;
```
becomes:
```
VAR_INPUT
test: BOOL := TRUE;
testNumberTwo:    BOOL   :=    TRUE   ;
```
but should be:
```
VAR_INPUT
	test: BOOL := TRUE;
	testNumberTwo: BOOL := TRUE;
```
or (maybe via setting):
```
VAR_INPUT
	test: BOOL		:= TRUE;
	testNumberTwo: BOOL	:= TRUE;
```

## Example 2:
```
CASE test OF
	1   :
		// something
	2:
		// something
```
becomes:
```
CASE test OF
	1   :
		// something
	2 :
		// something
```
but should be:
```
CASE test OF
	1:
		// something
	2:
		// something
```

## Example 3:
```
(*Comment*)
IF (something) THEN (*Comment*)
```
becomes:
```
(*Comment *)
IF (something) THEN (* Comment *)
```
but should be:
```
(* Comment *)
IF (something) THEN (* Comment *)
```

## Issue
On this line change csb to csa:
https://github.com/Serhioromano/vscode-st/blob/74eb30d77ca298ebcb84606b9d820b0329b6ab07/src/formatter.ts#L110
This should fix Example 3 and partially Example 1 and 2.
I say partially because after the fix it correctly doesn't add a space in front of the ':' but it still does not remove redundant spaces in front of it.

**Comment by Ahrkylien** [comment]
The exception to the rule about the space before the colon is the type declaration (as far as I know).
```
TYPE SomeName :
(
);
END_TYPE
```

**Comment by Serhioromano** [comment]
Thank you for all your notes. I'll see what I can do. I am working on LSP for ST and after it is done formatting will be good but now I just RegEx parse and can do only so little.

**Comment by TheColonel2688** [comment]
@Ahrkylien 

Where is your source on this? You Say PLCOpen.org.

Are you referring to 61131-3 3rd Edition or an Etention Standard published by PLCOpen.org. If so I would love to see this extension of the standard.

**Comment by Ahrkylien** [comment]
@TheColonel2688 
I got it from here https://plcopen.org/system/files/downloads/plcopen_coding_guidelines_version_1.0.pdf on page 108. But I also looked at how codesys 3 does stuff (space before the colon in the type declaration is based on codesys 3)

**Comment by TheColonel2688** [comment]
> @TheColonel2688 
> I got it from here https://plcopen.org/system/files/downloads/plcopen_coding_guidelines_version_1.0.pdf on page 108. But I also looked at how codesys 3 does stuff (space before the colon in the type declaration is based on codesys 3)

@Ahrkylien thanks for the Link!

**Comment by Serhioromano** [comment]
I did what is possible to do in 1.14.23
