### ISSUE TITLE
END_PROPERTY, SET, GET ??

### ISSUE THREAD

**Issue by TheColonel2688** [Serhioromano/vscode-st#56]
It doesn't seem like these Keywords are supported, or at least they dont work consistently.

- END_PROPERTY
- SET (*For Property*)
- GET (*For Property*)

**Comment by Serhioromano** [comment]
Please write an example of code with all those keywords. How that looks?

**Comment by Serhioromano** [comment]
@TheColonel2688 I would add it if you would add examples of syntax for GET and SET. Is there END_GET? 

```
SET : PropertyName

END_SET
```

Somthing like that?

**Comment by Serhioromano** [comment]
Done.

**Comment by TheColonel2688** [comment]
I am sorry for never commenting back.

I think the best syntax for this would be.

PROPERTY *Name* : *Type*
    SET
    END_SET
    GET
    END_GET
END_PROPERTY

I think this would be the closest to Codesys syntax. Codesys doesn't have a text-only format defined for Properties as of right now, But I assume they will have one for Codesys GO!

**Comment by Serhioromano** [comment]
Ok, I have added it according to your example. v1.12.25. Let's see if something change I'll update.
