### ISSUE TITLE
Support for CLASS .. END_CLASS

### ISSUE THREAD

**Issue by ghost** [Serhioromano/vscode-st#58]
Is it possible to add support for `CLASS` / `END_CLASS`, especially in the context of the outline feature?
I tried it myself and added `CLASS` / `END_CLASS` wherever `FUNCTION` / `END_FUNCTION` is used, but I broke the syntax highlighting feature and did not get the outline feature working.

**Comment by Serhioromano** [comment]
Created new release 1.12.18. Try it.

**Comment by Serhioromano** [comment]
Do not forget to rate this extension. Link is above.
