### ISSUE TITLE
Notification "This file not a structured text language!"

### ISSUE THREAD

**Issue by tkucic** [Serhioromano/vscode-st#6]
The notification "This file not a structured text language!" keeps appearing everytime I change files for example python -> StCode file and vice versa. Can you make a configuration parameter for this or delete it completely?
![image](https://user-images.githubusercontent.com/30636183/44109853-c5c19e26-a006-11e8-96cf-3aeb870b4c86.png)

**Comment by Serhioromano** [comment]
Update to v 1.2.3. Should be fixed.
