### ISSUE TITLE
repository link in extension details page broken

### ISSUE THREAD

**Issue by msftrncs** [Serhioromano/vscode-st#8]
The link to this repository in the extension details page appears to be broken, causes a "this file needs a app" dialog.   I haven't gotten that on anyone else's extensions.

![image](https://user-images.githubusercontent.com/26179051/44437787-99882200-a581-11e8-8bc9-ed5d316653c6.png)

**Comment by Serhioromano** [comment]
Fixed in next release. Thank you.
